loci:
  - chr1
  - chr2

data:
  controls:
    muscle:
      label: "Muscle"
      description: "36 samples"
      splice_junctions: out.tab
      coverage: muscle.bigWig

    fibroblasts:
      label: "Fibroblasts"
      description: "36 samples"
      splice_junctions: out.tab
      coverage: muscle.bigWig

    blood:
      label: "Blood"
      description: "36 samples"
      splice_junctions: out.tab
      coverage: muscle.bigWig

  samples:
    RGP_94_1:
      label: "RGP_94_1"
      splice_junctions: out.tab
      coverage: muscle.bigWig
    RGP_94_2:
      label: "RGP_94_2"
      splice_junctions: out.tab
      coverage: muscle.bigWig
      vcf: bla.vcf
    RGP_94_3:
      label: "RGP_94_3"
      splice_junctions: out.tab
      coverage: muscle.bigWig
      vcf: bla.vcf
