referenceGenome: "38"

currentLocus: "chr1:50000-51000"

loci:
  - chr1
  - chr2

samplesInfo:
  controls:
    muscle:
      order: 1
      label: "Muscle"
      description: "100 GTEx skeletal muscle samples"
      spliceJunctions_bed: gs://macarthurlab-rnaseq/GTEx_ref_data/muscle_100_GTEx_samples.SJ.out.tab.bed.gz
      coverage_bigWig: gs://macarthurlab-rnaseq/GTEx_ref_data/muscle_100_GTEx_samples.bigWig

    blood:
      order: 2
      label: "Blood"
      description: "100 GTEx whole blood samples"
      spliceJunctions_bed: gs://macarthurlab-rnaseq/GTEx_ref_data/blood_100_GTEx_samples.SJ.out.tab.bed.gz
      coverage_bigWig: gs://macarthurlab-rnaseq/GTEx_ref_data/blood_100_GTEx_samples.bigWig

    fibroblasts:
      order: 3
      label: "Fibroblasts"
      description: "100 GTEx cultured fibroblast samples"
      spliceJunctions_bed: gs://macarthurlab-rnaseq/GTEx_ref_data/fibs_100_GTEx_samples.SJ.out.tab.bed.gz
      coverage_bigWig: gs://macarthurlab-rnaseq/GTEx_ref_data/fibs_100_GTEx_samples.bigWig

  samples:
    RGP_94_1:
      label: "RGP_94_1"
      spliceJunctions_bed: out.tab
      coverage_bigWig: gs://macarthurlab-rnaseq/bigWig/VCGS_FAM58_181_R1.bigWig
      vcf: gs://
      bam:

    RGP_94_2:
      label: "RGP_94_2"
      spliceJunctions_bed: out.tab
      coverage_bigWig: gs://macarthurlab-rnaseq/bigWig/VCGS_FAM58_181_R1.bigWig
      vcf: gs://
      bam:

    RGP_94_3:
      label: "RGP_94_3"
      spliceJunctions_bed: out.tab
      coverage_bigWig: gs://macarthurlab-rnaseq/bigWig/VCGS_FAM58_181_R1.bigWig
      vcf: gs://
      bam:
