referenceGenome: "38"

currentLocus: "chr1:50000-51000"

loci:
  - chr1
  - chr2

samplesInfo:
  controls:
    muscle:
      order: 1
      label: "Muscle"
      description: "36 samples"
      splice_junctions: out.tab
      coverage: gs://macarthurlab-rnaseq/bigWig/VCGS_FAM49_153_R1.bigWig

    blood:
      order: 2
      label: "Blood"
      description: "36 samples"
      splice_junctions: out.tab
      coverage: gs://macarthurlab-rnaseq/bigWig/VCGS_FAM4_13_2.bigWig

    fibroblasts:
      order: 3
      label: "Fibroblasts"
      description: "36 samples"
      splice_junctions: out.tab
      coverage: gs://macarthurlab-rnaseq/bigWig/VCGS_FAM52_162_3.bigWig

  samples:
    RGP_94_1:
      label: "RGP_94_1"
      splice_junctions: out.tab
      coverage: gs://macarthurlab-rnaseq/bigWig/VCGS_FAM58_181_R1.bigWig
      bam: gs://
    RGP_94_2:
      label: "RGP_94_2"
      splice_junctions: out.tab
      coverage: gs://macarthurlab-rnaseq/bigWig/VCGS_FAM150_468_2.bigWig
      vcf: bla.vcf
    RGP_94_3:
      label: "RGP_94_3"
      splice_junctions: out.tab
      coverage: gs://macarthurlab-rnaseq/bigWig/VCGS_FAM12_36_2.bigWig
      vcf: bla.vcf
